Add categories table in migration file to group competencies
OpenTree-Education/rhizone-lms pull request #399
Opened 2022-06-23 20:52 UTC by sheacronin

## Proposed changes

Closes #369 . This pull request adds a categories table to the database with the following fields: id, label, description, image_url, created_at, and updated_at. This categories table will be used by the competencies table to group the competencies by category. image_url is the only optional column on the table, and the frontend should be able to handle a category without an image. This is the second pull request for this issue, now with the updated ES Lint checks from the newest main branch.

## Checklist

- [x] Are the issues being addressed linked to this PR?
- [x] Do all commit messages start with the issue number?
- [x] Are all code changes sufficiently tested?
- [x] Are there screenshots for UI changes?

2022-06-23 20:59 UTC, daveytech requested changes
Great! As there are no official testing files for migrations and we do not have a staging environment, one suggestion is for the personal responsible for the PR to add the code blocks of the output of their migration files to the PR. I know you've already tested it but for practice are you able to add the code block as a comment before you merge? Other than that it satisfies the issue.

2022-06-23 20:59 UTC, Nazanin-Rezaei approved these changes
Category table  with image_url optional feature and created and updated features set to current-timestamp looks functional.

2022-06-23 21:07 UTC, achichikalova commented on db/migration/V015__create_categories_table.sql
> +  image_url VARCHAR(255),
Do we need to make it required because we decided on the categories' images?

2022-06-23 21:09 UTC, sheacronin commented
Here is a screenshot of the migration file running successfully.
<img width="646" alt="flyway_build" src="https://user-images.githubusercontent.com/67711077/175399957-b207a41b-6d9b-4541-bb01-930df198fb53.png">

Here is what the database looks like with the new table and its columns.
<img width="653" alt="db_tables" src="https://user-images.githubusercontent.com/67711077/175399916-e1e731f1-b6e1-4f0c-b308-9590b5c12742.png">

2022-06-23 21:16 UTC, daveytech commented
@sheacronin Yes Screenshot works! Thank you

2022-06-23 21:17 UTC, daveytech approved these changes
Thanks for the screenshots!

2022-06-24 17:09 UTC, achichikalova approved these changes

2022-06-24 17:09 UTC, merged