Hover over the activities in agenda shows hand pointer
OpenTree-Education/rhizone-lms pull request #472
Opened 2022-12-05 20:55 UTC by Prabhj33t

## Proposed changes

Resolved  #449 issue with text cursor showing up while hovering on the activities in the agenda. The cursor changes to a hand pointer now.

## Checklist

- [x] Are the issues being addressed linked to this PR?
- [x] Do all commit messages start with the issue number?
- [x] Are all code changes sufficiently tested?
- [ ] Are there screenshots for UI changes?

2022-12-06 17:58 UTC, daveytech requested changes
Great work on the ticket Prabh! Could you please include a screenshot for the PR before we accept?

It looks good otherwise!

2022-12-06 19:01 UTC, wendyyng approved these changes
I git checkout to the branch and it worked as expected - hovering over the events in agenda view shows a hand pointer. I also ran yarn delint and it didn't change any formatting.

2022-12-06 19:16 UTC, Prabhj33t commented
Here is the screenshot.
<img width="1434" alt="MEScree" src="https://user-images.githubusercontent.com/105026997/206001772-3ca5b55f-dd10-4a2a-9ed5-9282fbdf47e5.png">

2022-12-06 20:21 UTC, daveytech approved these changes
Awesome work! Thank you for including the screenshot. This is good to go!

2022-12-06 20:38 UTC, camianderson approved these changes
Approved to merge!

2022-12-06 20:38 UTC, camianderson commented on webapp/src/index.css
> +  cursor: pointer;
Nice work!

2022-12-07 18:27 UTC, rrabinovitch approved these changes
The changes work as expected on my local machine.
My only note is that the PR title doesn't include the relevant issue number, so we might want to edit the title before merging.

2022-12-07 21:35 UTC, merged