454 updating participantactivities completion status
OpenTree-Education/rhizone-lms pull request #477
Opened 2022-12-07 20:57 UTC by phoebehala

## Proposed changes

- A `getParticipantActivityId` function returns the participant activity ID if it exists, otherwise it returns null.
- A `getParticipantActivityCompletion` function returns the completion status (either true or false) of the specific activity.
- A `setParticipantActivityCompletion` function is to set/update the completion status of the specific activity.
-  The JsDoc function headers for each of functions above.
-  The JEST test functions for each of functions above.

## Checklist

- [x] Are the issues being addressed linked to this PR?
- [x] Do all commit messages start with the issue number?
- [x] Are all code changes sufficiently tested?
- [ ] Are there screenshots for UI changes?

2022-12-07 21:21 UTC, ChainShoe-Z commented
All tests are passed, just remove the comment and run delint again!

2022-12-07 21:43 UTC, daveytech requested changes
Great work on this ticket. One comment left on the file that should probably be cleaned up. And then a question about the choice on the knex query. Other than that should be good for a merge!

2022-12-07 22:09 UTC, phoebehala commented on api/src/services/programsService.ts
> +    .merge({ completed: completed });
`.onConflict()` if conflict occurs after inserting a new row which means it already has a row matching 'program_id', 'principal_id', 'activity_id'),
then`.merge({})` update with different data to the insert( update 'completed' value to what we receive from a user)

Refer to https://knexjs.org/guide/query-builder.html#insert

2022-12-07 22:35 UTC, daveytech commented on api/src/services/programsService.ts
> +    .merge({ completed: completed });
Thank you for the context!

2022-12-07 23:00 UTC, daveytech approved these changes
Thanks for cleaning that up!

2022-12-07 23:00 UTC, wendyyng commented on api/src/models.d.ts
> +export interface participantActivities {
I think participantActivities should be capitalized like other types

2022-12-07 23:14 UTC, rrabinovitch requested changes
Great work on this ticket. I know there were a lot of back and forths to get to this point.
I left a few comments that are hopefully quick to address. Other than that, the tests all run successfully on my end.

2022-12-07 23:14 UTC, rrabinovitch commented on api/src/services/programsService.ts
> + * @returns {Object} - if successful, the ID of the record in the table
same question here as what I commented on L324

2022-12-07 23:14 UTC, rrabinovitch commented on api/src/services/__tests__/programsService.ts
> +  participantActivities,
when Wendy's comment in the models file is addressed, the capitalization should be addressed here as well

2022-12-08 01:22 UTC, seidior commented on api/src/services/programsService.ts
> +    .merge({ completed: completed });
@daveytech This was my suggestion. It's the officially-sanctioned way in Knex to do an upsert.

2022-12-08 19:17 UTC, rrabinovitch approved these changes

2022-12-08 19:19 UTC, rrabinovitch approved these changes
thanks for addressing my previous comments. it looks like this branch needs to be updated to align with the latest version of main and then hopefully it's ready to merge the PR.

2022-12-08 20:02 UTC, merged