#517 Define routes for assessments feature
OpenTree-Education/rhizone-lms pull request #531
Opened 2023-03-07 21:16 UTC by Paryssatis

#517 For each route defined in the list of routes that was in #506, the information being sent to the backend and retrieved from the backend needs to be defined in a structure so that we can wire up the backend to the frontend.

## Checklist

- [x] Related issue appears at beginning of pull request title with pound sign, and title describes the changes being proposed.
- [x] Related issue is linked in pull request description using [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] The appropriate label has been chosen for this pull request.
- [x] The correct project has been selected for this pull request.
- [x] All commits in this branch, including merge commits, begin with the issue number and a pound sign.
- [x] Tests have been added, where appropriate; or, no tests are relevant for this pull request.
- [x] This pull request contains UI changes, and screenshots of those UI images appear below; or, this pull request contains no UI changes.

2023-03-07 22:24 UTC, seidior requested changes
I'm only going to comment on `models.d.ts`, since your work is duplicated between the two files. For the most part, you've got the data types in place, so there's just a few minor comments to bring it closer to the spec.

You've also defined a few extraneous data types that were not called for in the document. If you notice, we don't define single-member data types anywhere else in the model file; when crafting code that is like other code that we have, make sure you follow the same design patterns and code style that we use elsewhere in our application.

Once you make the changes requested and you copy them over to the `api.d.ts` file, please let me know and I'll take another look at the file.

Thank you for your work on this!

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +  answers?: Answer[];
`Answer` here is an object type, one that we also define in this file. As per our feedback earlier today, I would like you to have the interface definition for `Answer` appear above `Question` in this file; likewise, any other object types being referenced in any of the other interfaces should appear above them in this file.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +  id?: number;
As mentioned previously, for all data types that have an `id` field, the `id` field should display first.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +  assessment_question_id: number;
This field does not appear in the data types Google Doc I'm referencing. What is this field, and what information does it reference?

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +  questions: Question[];
This parameter should be optional.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +    | AssessmentSubmissionsSummary
This field should not be prepended with the `|` (pipe) symbol. It should only appear between `AssessmentSubmissionsSummary` and `FacilitatorAssessmentSubmissionsSummary`.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +export interface ProgramAvailableAssessmentsSummary {
Let's rename this `AssessmentSummary`.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +export interface AssessmentResponses {
Let's switch from the plural `AssessmentResponses` to the singular `AssessmentResponse`.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +  state_id: number;
We already have `assessment_submission_state`; therefore, we don't need `state_id` as well.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +export interface ProgramSubmittedAssessments {
Let's rename this `SubmittedAssessment`.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +export interface AssessmentSubmission {
We're already defining this on line 152 above. Is there a reason we need to define it again?

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +export interface ProgramSubmittedAssessments {
Let's remove this as well, since we're already defining it above on line 164.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +export interface AssessmentSubmission {
Let's remove this, the third definition of AssessmentSubmission.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +export interface DraftProgramAssessment {
Let's remove this as well. This is fundamentally the same data type as a `SubmittedAssessment` and therefore doesn't need another name.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +export interface ProgramCertificate {
We don't need a data type for this. This may be safely removed.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +export interface NewProgramAssessment {
We don't need a data type for this. This may be safely removed.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +export interface EditProgramAssessment {
We don't need a data type for this. This may be safely removed.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +export interface DeleteProgramAssessment {
We don't need a data type for this. This may be safely removed.

2023-03-07 22:24 UTC, seidior commented on api/src/models.d.ts
> +export interface SubmitProgramAssessment {
We don't need a data type for this. This may be safely removed.

2023-03-08 00:05 UTC, seidior approved these changes
You have adequately addressed the changes I have previously requested, and your code sufficiently addresses and resolves the issue in the ticket. I am approving it for merger with the feature branch.

Thanks so much team! Great work.

2023-03-08 20:45 UTC, Awatanka approved these changes
Great job with the models that were created for our router!

2023-03-08 20:47 UTC, merged