561 getcurriculumassessmentid route
OpenTree-Education/rhizone-lms pull request #566
Opened 2023-03-27 20:22 UTC by kaiyolau

## Proposed changes

This pull request close #561  which adds a route for details of a specific CurriculumAssessment. 
It created these scenarios:

- The endpoint for this route handler is '/curriculum/:curriculumAssessmentId', where `:curriculumAssessmentId` is a URL parameter that represents the ID of the `CurriculumAssessment`.
- 
- The programId associated with the curriculumAssessmentId is retrieved using the `getProgramIdByProgramAssessmentId()` function.
- 
- The `programRole` of the authenticated user for this program is retrieved using the `getPrincipalProgramRole()` function.
- 
- If the `programRole` is not defined or is 'Participant', a UnauthorizedError is thrown with an appropriate error message.
- 
- The curriculumAssessment object associated with the `curriculumAssessmentId` is retrieved using the `getCurriculumAssessment()` function.

There is also one new function created in the Service file :

`getProgramIdByProgramAssessmentId`

## Checklist

- [x] Related issue appears at beginning of pull request title with pound sign, and title describes the changes being proposed.
- [x] Related issue is linked in pull request description using [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] The appropriate label has been chosen for this pull request.
- [x] The correct project has been selected for this pull request.
- [x] All commits in this branch, including merge commits, begin with the issue number and a pound sign.
- [x] Tests have been added, where appropriate; or, no tests are relevant for this pull request.
- [x] This pull request contains UI changes, and screenshots of those UI images appear below; or, this pull request contains no UI changes.

2023-03-27 22:22 UTC, seidior requested changes
Hi Kyle! I've brought your branch up to date with the #515 branch a couple of times so that you have the latest of what we worked on in the #sequoia-room today.

I liked that you caught some variable naming errors, but it was the change to the column name that we were selecting that was causing your tests to fail.

You had selected the pull request destination to `main` instead of to the #515 branch, so your pull request had way more changed files than what was necessary. I've since updated this to have the correct destination.

I've left you some feedback on how to proceed with this ticket. Let me know if you have any questions.

2023-03-27 22:22 UTC, seidior commented on api/src/middleware/assessmentsRouter.ts
> +      curriculumAssessmentIdParsed
I don't think I'm understanding your logic here. Why would we call a function called `getProgramIdByProgramAssessmentId` with a variable called `curriculumAssessmentIdParsed`?

2023-03-27 22:22 UTC, seidior commented on api/src/middleware/assessmentsRouter.ts
> +    );
I... think? I'm following your logic here, but the fatal flaw here is that you can't directly get a program ID given a curriculum assessment ID.

Instead, you'll want to check L143 through L161 to see how we tackled this logic with Paryssa's route.

2023-03-27 22:22 UTC, seidior commented on api/src/services/assessmentsService.ts
> +  AssessmentId: number
I don't believe we need this function at all.

2023-03-27 23:34 UTC, kaiyolau commented
@seidior I just updated the new logic for #561

2023-03-28 01:29 UTC, seidior requested changes
Hi @kaiyolau! Thanks for updating the logic. I need you to now write tests for your route as well as for any service file functions you call from your route please.

2023-03-29 13:21 UTC, merged